@startuml
'https://plantuml.com/component-diagram

package "Backend" {
    folder "Controladores" {
        [ControlDirecciones]
        [ControlDomicilios]
        [ControladorEmpleados]
        [ControladorEscolaridades]
        [ControlEstados]
        [ControladorPersonas]
        [ControladorPuestos]
        [ControladorRegiones]
        [ControladorRoles]
        [ControladorSubdirecciones]
        [ControlTiposPlazas]
    }

        folder "Servicios" {
            folder "Entidades" {
                            [Direccion]
                            [Domicilio]
                            [Empleado]
                            [Escolaridad]
                            [Estado]
                            [Persona]
                            [Puesto]
                            [Region]
                            [Rol]
                            [Subdireccion]
                            [TipoPlaza]
                        }

            folder "Business"{
                [ServicioDirecciones]
                                    [ServicioDomicilios]
                                    [ServicioEmpleados]
                                    [ServicioEscolaridades]
                                    [ServicioEstados]
                                    [ServicioPersonas]
                                    [ServicioPuestos]
                                    [ServicioRegiones]
                                    [ServicioRoles]
                                    [ServicioSubdirecciones]
                                    [ServicioTiposPlazas]
            }
    }


        folder "Repositorios" {
                [RepositorioDirecciones]
                [RepositorioDomicilios]
                [RepositorioEmpleados]
                [RepositorioEscolaridades]
                [RepositorioEstados]
                [RepositorioPersonas]
                [RepositorioPuestos]
                [RepositorioRegiones]
                [RepositorioRoles]
                [RepositorioSubdirecciones]
                [RepositorioTiposPlazas]
            }
}





[ControlDirecciones] -down-> [ServicioDirecciones]
[ControlDomicilios] -down-> [ServicioDomicilios]
[ControladorEmpleados] -down-> [ServicioEmpleados]
[ControladorEscolaridades] -down-> [ServicioEscolaridades]
[ControlEstados] -down-> [ServicioEstados]
[ControladorPersonas] -down-> [ServicioPersonas]
[ControladorPuestos] -down-> [ServicioPuestos]
[ControladorRegiones] -down-> [ServicioRegiones]
[ControladorRoles] -down-> [ServicioRoles]
[ControladorSubdirecciones] -down-> [ServicioSubdirecciones]
[ControlTiposPlazas] -down-> [ServicioTiposPlazas]




[RepositorioDirecciones] <-down- [ServicioDirecciones]
[ServicioDomicilios] <-up- [RepositorioDomicilios]
[ServicioEmpleados] <-up- [RepositorioEmpleados]
[ServicioEscolaridades] <-up- [RepositorioEscolaridades]
[ServicioEstados] <-up- [RepositorioEstados]
[ServicioPersonas] <-down- [RepositorioPersonas]
[ServicioPuestos] -down-> [RepositorioPuestos]
[ServicioRegiones] -down-> [RepositorioRegiones]
[ServicioRoles] -down-> [RepositorioRoles]
[ServicioSubdirecciones] -down-> [RepositorioSubdirecciones]
[ServicioTiposPlazas] -down-> [RepositorioTiposPlazas]




@enduml