openapi: 3.1.0
tags:
  - name: Empleados
    description: Funciones sobre empleados de la DGEC
  - name: Escolaridades
    description: Funciones sobre niveles escolares
  - name: Personas
    description: Funciones sobre personas
  - name: Roles
    description: Funciones sobre roles
  - name: TiposPlazas
    description: Funciones sobre los tipos de plazas
x-stoplight:
  id: q54z857tlv2o2
info:
  title: Sistema Integración Divisional API
  version: '1.0'
  contact:
    name: Proyect SID
    email: cbi2193011275@izt.uam.mx
    url: 'https://github.com/migueGO98/ProyectoSID'
  description: Proyecto personal de Miguel Guzman. "Sistema de Integración Divisional" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
  license:
    name: MIT
    url: 'https://migueGO98.github.io/license'
  summary: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /api/empleados:
    post:
      summary: Crear un nuevo empleado
      tags:
        - Empleados
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empleado'
          headers:
            Location:
              schema:
                type: string
              description: Ubicación del empleado creado
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: crearEmpleado
      x-stoplight:
        id: 6a088zwq07klw
      description: Crea un nuevo empleado
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEmpleado'
            examples: {}
        description: ''
        required: true
    parameters: []
  /api/escolaridades/niveles:
    get:
      summary: Recuperar niveles escolares
      tags:
        - Escolaridades
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registros'
                  x-stoplight:
                    id: ydit3efh5ekd2
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: recuperarNivelesEscolares
      x-stoplight:
        id: 12i98woyeppwa
      description: Recupera los niveles escolares permitidos por el sistema
  /api/escolaridades/niveles/estados:
    get:
      summary: Recuperar estados niveles escolares
      tags:
        - Escolaridades
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registros'
                  x-stoplight:
                    id: xnfkv4e7hdv0w
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: recuperarEstadosNivelesEscolares
      x-stoplight:
        id: bb3c850gnrndh
      description: 'Recupera los estados de los niveles escolares permitidos por el sistema '
    parameters: []
  /api/personas/generos:
    get:
      summary: Recuperar generos para una persona
      tags:
        - Personas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registros'
                  x-stoplight:
                    id: is13k7cz5nxkw
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: recuperarGeneros
      x-stoplight:
        id: q88dlsgtsqtn2
      description: Recupera los géneros de una persona permitidos por el sistema
  /api/personas/estadosCiviles:
    get:
      summary: Recupera los estados civiles de una persona
      tags:
        - Personas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registros'
                  x-stoplight:
                    id: 36afykzvneb21
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: recuperarEstadosCiviles
      x-stoplight:
        id: j8e12vndanrtq
      description: Recupera los estados civiles de una persona permitidos por el sistema
  /api/empleados/motivosBaja:
    get:
      summary: Recuperar motivos de baja
      tags:
        - Empleados
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registros'
                  x-stoplight:
                    id: hchhjxjdjf6f5
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: recuperarMotivosBaja
      x-stoplight:
        id: 76bkg7log5l7o
      description: Recupera los motivos de bajas de un empleado permitidos por el sistema
  /api/roles:
    get:
      summary: Recuperar roles
      tags:
        - Roles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rol'
                  x-stoplight:
                    id: 3l9rrjpewfkzp
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: recuperarRoles
      x-stoplight:
        id: cfdso2buckduj
      description: Recupera los roles registrados en el sistema
  /api/tipos-plazas:
    get:
      summary: Recuperar tipos de plazas
      tags:
        - TiposPlazas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registros'
                  x-stoplight:
                    id: paojb7zlxa5jz
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: recuperarTiposPlazas
      x-stoplight:
        id: 0zvrwsofztb5s
      description: Recupera los tipos de plazas registrados en el sistema
components:
  schemas:
    NewEmpleado:
      title: NewEmpleado
      x-stoplight:
        id: tj1ar29q44f77
      type: object
      required:
        - persona
        - domicilio
        - escolaridades
        - fechaIngreso
        - idTipoPlaza
        - idRegion
        - idDireccion
        - idSubdireccion
        - idPuesto
        - roles
      properties:
        persona:
          $ref: '#/components/schemas/Persona'
          x-stoplight:
            id: 2hgbqzq3o3gtk
        domicilio:
          $ref: '#/components/schemas/Domicilio'
          x-stoplight:
            id: acomoy90v5w7j
        escolaridades:
          type: array
          x-stoplight:
            id: jnj1lgomijflr
          minItems: 1
          maxItems: 5
          x-constraints: '@NonNullElement'
          items:
            $ref: '#/components/schemas/Escolaridad'
            x-stoplight:
              id: ypsxrwa91td9u
        fechaIngreso:
          type: string
          x-stoplight:
            id: pw4oaxlrpk2e2
          format: date
          example: '2020-01-01'
        idTipoPlaza:
          x-stoplight:
            id: ifi0xx9kex23v
          type: string
          pattern: '^[a-zA-Z0-9]+$'
          example: SPC
          x-constraints: '@NotBlank @NotEmpty'
        idRegion:
          type: string
          x-stoplight:
            id: f62jthv07ffhl
          pattern: '^[a-zA-Z0-9]+$'
          example: oc
          x-constraints: '@NotBlank @NotEmpty'
        idDireccion:
          type: string
          x-stoplight:
            id: i1iswdtq8on34
          pattern: '^[a-zA-Z0-9]+$'
          example: DGEC
          x-constraints: '@NotBlank @NotEmpty'
        idSubdireccion:
          type: string
          x-stoplight:
            id: 6lh2qgh72njny
          pattern: '^[a-zA-Z0-9]+$'
          example: SUBAdmonOC
          x-constraints: '@NotBlank @NotEmpty'
        idPuesto:
          type: string
          x-stoplight:
            id: z3iuknlq4r94q
          pattern: '^[a-zA-Z0-9]+$'
          example: na1
          x-constraints: '@NotBlank @NotEmpty'
        roles:
          type: array
          x-stoplight:
            id: qh38vks47p61n
          minItems: 1
          maxItems: 10
          x-constraints: '@NonNullElement'
          items:
            x-stoplight:
              id: scggn1zeiuadl
            type: string
            example: rh1
            pattern: '^[a-zA-Z0-9]+$'
            x-constraints: '@NotBlank @NotEmpty'
    Domicilio:
      title: DomicilioEmpleado
      x-stoplight:
        id: yql0d9fa0qfo1
      type: object
      required:
        - calle
        - codigoPostal
        - colonia
        - municipio
        - ciudad
        - estado
      properties:
        calle:
          type: string
          x-stoplight:
            id: bidhdl0twq0b9
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Izta No 40
          x-constraints: '@NotBlank @NotEmpty'
        codigoPostal:
          type: string
          x-stoplight:
            id: a3x7dkyt3wjae
          minLength: 5
          maxLength: 5
          example: '01111'
          x-constraints: '@NotBlank @NotEmpty @NumericOnly'
        colonia:
          type: string
          x-stoplight:
            id: djarovc2rpflv
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Prolongación de Noñora
          x-constraints: '@NotBlank @NotEmpty'
        municipio:
          type: string
          x-stoplight:
            id: dnok4daqngu4d
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Gustavo A. Madero
          x-constraints: '@NotBlank @NotEmpty'
        ciudad:
          type: string
          x-stoplight:
            id: 1f2n8slgvpkfu
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Ciudad de México
          x-constraints: '@NotBlank @NotEmpty'
        estado:
          type: string
          x-stoplight:
            id: 93imtpm3u3p6l
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Ciudad de México
          x-constraints: '@NotBlank @NotEmpty'
    Persona:
      title: Persona
      x-stoplight:
        id: w5upcksed0scb
      type: object
      required:
        - nombre
        - apellidoPaterno
        - apellidoMaterno
        - curp
        - rfc
        - numeroSeguroSocial
        - fechaNacimiento
        - genero
        - telefonoPersonal
        - correoElectronicoPersonal
        - estadoCivil
        - hijos
        - contactoEmergenciaNombre
        - contactoEmergenciaTelefono
      properties:
        nombre:
          type: string
          x-stoplight:
            id: 1i7ebs4qwdbkq
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Fabian Carlos
          x-constraints: '@NotBlank @NotEmpty'
        apellidoPaterno:
          type: string
          x-stoplight:
            id: 94jnyfa3k6rqa
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: de la López
          x-constraints: '@NotBlank @NotEmpty'
        apellidoMaterno:
          type:
            - string
            - 'null'
          x-stoplight:
            id: kmlxoqjb3lf9r
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Estrada
          x-constraints: '@NotBlank @NotEmpty'
        curp:
          type: string
          x-stoplight:
            id: qbsccpyrbfoay
          minLength: 18
          maxLength: 18
          pattern: '^[a-zA-ZÑñ]{4}\d{6}[a-zA-ZÑñ]{6}[a-zA-Z0-9Ññ]\d$'
          example: LOEF111111HDFASD01
          x-constraints: '@NotBlank @NotEmpty'
        rfc:
          type: string
          x-stoplight:
            id: wxl0c9s4k7w0c
          minLength: 13
          maxLength: 13
          pattern: '^[A-Za-z&ñÑ]{4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Za-z0-9]{2}[0-9Aa]$'
          example: loef111111fg9
          x-constraints: '@NotBlank @NotEmpty'
        numeroSeguroSocial:
          type: string
          x-stoplight:
            id: spq24ibgs5ty8
          minLength: 11
          maxLength: 11
          example: '11111111111'
          x-constraints: '@NotBlank @NotEmpty @NumericOnly'
        fechaNacimiento:
          type: string
          x-stoplight:
            id: sgzydws72hx8j
          format: date
          example: '2000-01-01'
        genero:
          $ref: '#/components/schemas/GeneroEnum'
          x-stoplight:
            id: hh6g2lif4vzhz
        telefonoPersonal:
          type: string
          x-stoplight:
            id: or7pwd0unwaka
          minLength: 10
          maxLength: 10
          example: '1234567890'
          x-constraints: '@NotBlank @NotEmpty @NumericOnly'
        correoElectronicoPersonal:
          type: string
          x-stoplight:
            id: 1p5pumjd6snhz
          format: email
          example: user@example.com
          x-constraints: '@NotBlank @NotEmpty'
        estadoCivil:
          $ref: '#/components/schemas/EstadoCivilEnum'
          x-stoplight:
            id: zntuk9p7zhpwp
        hijos:
          type: boolean
          x-stoplight:
            id: hogfnpvrnn4au
          default: false
        contactoEmergenciaNombre:
          type: string
          x-stoplight:
            id: nz3br88i2bgp5
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Martina Estrada Martínez
          x-constraints: '@NotBlank @NotEmpty'
        contactoEmergenciaTelefono:
          type: string
          x-stoplight:
            id: 3o9viaperyc06
          minLength: 10
          maxLength: 10
          example: '9876543210'
          x-constraints: '@NotBlank @NotEmpty @NumericOnly'
    Empleado:
      title: Empleado
      x-stoplight:
        id: 6w0d2ye2s4n6k
      type: object
      required:
        - idEmpleado
        - nombreCompleto
        - activo
        - fechaIngreso
        - idTipoPlaza
        - idRegion
        - idDireccion
        - idSubdireccion
        - idPuesto
        - roles
      properties:
        idEmpleado:
          type: string
          x-stoplight:
            id: 38afwu5wdbb4y
        nombreCompleto:
          type: string
          x-stoplight:
            id: 1ttctipmd7ccu
        activo:
          type: boolean
          x-stoplight:
            id: 3zpx9nwap4h07
        fechaIngreso:
          type: string
          x-stoplight:
            id: s16d5wqwy5rg0
          format: date
        idTipoPlaza:
          type: string
          x-stoplight:
            id: tmlbplh9oppnx
        idRegion:
          type: string
          x-stoplight:
            id: qq7w395bnycmu
        idDireccion:
          type: string
          x-stoplight:
            id: 2vluu69gkh6c1
        idSubdireccion:
          type: string
          x-stoplight:
            id: la7q29il78wgh
        idPuesto:
          type: string
          x-stoplight:
            id: s4l2zkg02a509
        roles:
          type: array
          x-stoplight:
            id: 2ebexb3jsrxpp
          items:
            x-stoplight:
              id: wp7u4acbwt3fb
            type: string
    Error:
      title: Error
      x-stoplight:
        id: xajwbur82fuw4
      type: object
      required:
        - codigo
        - mensaje
      properties:
        codigo:
          type: string
          x-stoplight:
            id: u1eba0v9n17w4
        mensaje:
          type: string
          x-stoplight:
            id: 06cmsn3mqy7m1
    GeneroEnum:
      title: GeneroEnum
      x-stoplight:
        id: x9szta9ltxpbz
      enum:
        - MASCULINO
        - FEMENINO
        - NO_BINARIO
        - OTRO
      example: MASCULINO
    Escolaridad:
      title: Escolaridad
      x-stoplight:
        id: yxrtoid4n6rj2
      type: object
      required:
        - nivel
        - carrera
        - estadoNivel
        - cedulaProfesional
      properties:
        nivel:
          $ref: '#/components/schemas/NivelesEscolaridadesEnum'
          x-stoplight:
            id: m6ocpf01asaf0
        carrera:
          type: string
          x-stoplight:
            id: ylz3r9h0kdcjm
          pattern: '^[\p{L}\s''-ñÑÁÉÍÓÚáéíóú]+$'
          example: Licenciatura en Computación
          x-constraints: '@NotBlank @NotEmpty'
        estadoNivel:
          $ref: '#/components/schemas/EstadosNivelesEscolaridadesEnum'
          x-stoplight:
            id: sqmdnf0tdf1cq
        cedulaProfesional:
          type:
            - string
            - 'null'
          x-stoplight:
            id: aqb2bqf26t0we
          minLength: 7
          maxLength: 8
          example: '12345678'
          x-constraints: '@NotBlank @NotEmpty @NumericOnly'
    NivelesEscolaridadesEnum:
      title: NivelesEscolaridadesEnum
      x-stoplight:
        id: fdm9gpiywfte3
      enum:
        - TECNICO
        - LICENCIATURA
        - MAESTRIA
        - ESPECIALIDAD
        - DOCTORADO
        - BACHILLERATO
        - DIPLOMADO
      example: LICENCIATURA
    EstadosNivelesEscolaridadesEnum:
      title: EstadosNivelesEscolaridadesEnum
      x-stoplight:
        id: lp23oi2nezd0u
      enum:
        - CREDITOS_CUBIERTOS
        - CERTIFICADO
        - PASANTE
        - TITULADO
        - TRAMITE_TITULACION
        - TRUNCA
      example: TRAMITE_TITULACION
    Registros:
      title: Registros
      x-stoplight:
        id: dskx3lmhwlqty
      type: object
      required:
        - id
        - descripcion
      properties:
        id:
          type: string
          x-stoplight:
            id: xh17snizskvlc
        descripcion:
          type: string
          x-stoplight:
            id: cgh4j5oaj60pv
    EstadoCivilEnum:
      title: EstadoCivilEnum
      x-stoplight:
        id: kho7ayv5c1fj4
      enum:
        - CASADO
        - CASADA
        - SOLTERO
        - SOLTERA
        - VIUDO
        - VIUDA
        - SEPARADO
        - SEPARADA
        - DIVORCIADO
        - DIVORCIADA
        - UNION_LIBRE
      example: SOLTERO
    MotivoBajaEnum:
      title: MotivoBajaEnum
      x-stoplight:
        id: olyxewhx5e1vk
      enum:
        - TERMINO_CONTRATO
        - RENUNCIA
        - LIQUIDACION
    Rol:
      title: Rol
      x-stoplight:
        id: biwwue5e63r0u
      type: object
      required:
        - idRol
        - descripcion
      properties:
        idRol:
          type: string
          x-stoplight:
            id: c4zd8ds89lf29
        descripcion:
          type: string
          x-stoplight:
            id: 5fb5v3omhsc6j
  requestBodies: {}
  responses: {}
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
x-constraints: x-constraints
security:
  - jwt: []
