openapi: 3.1.0
tags:
  - name: Empleados
    description: Funciones sobre empleados de la DGEC
x-stoplight:
  id: zub4eo4y641wl
info:
  title: Sistema Integración Divisional API
  version: '1.0'
  contact:
    name: Proyect SID
    email: gzm98.miguel@gmail.com
    url: 'https://github.com/migueGO98/ProyectoSID'
  description: Proyecto personal de Miguel Guzman. "Sistema de Integración Divisional" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
  license:
    name: MIT
    url: 'https://migueGO98.github.io/license'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/empleados:
    post:
      summary: Crear nuevo empleado
      tags:
        - Empleados
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Empleado'
          headers:
            Location:
              schema:
                type: string
              description: Ubicación del empleado creado
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: crearEmpleado
      x-stoplight:
        id: kl20364k5fm8r
      description: Crea un nuevo empleado
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEmpleado'
        description: ''
        required: true
    parameters: []
components:
  schemas:
    NewEmpleado:
      title: NewEmpleado
      x-stoplight:
        id: 8yun4ny2yjvcl
      type: object
      examples:
        - persona:
            nombre: Fabian
            apellidoPaterno: Cortez
            apellidoMaterno: Estrada
            fechaNacimiento: '1998-01-01'
            edad: 26
            genero: Masculino
            numeroSeguroSocial: '12345678965'
            rfc: COEF980101ABC
            curp: COEF980101HDFABCXX
            correoElectronico: fabian.cortez@correo.com
            telefono: '5512345678'
            contactoEmergenciaNombre: Carolina Cortez Estrada
            contactoEmergenciaTelefono: '5598745632'
          domicilio:
            calle: Prolongación
            colonia: Lomas de Prolongación
            codigoPostal: '01474'
            municipio: Iztapalapa
            estado: CDMX
            pais: México
          escolaridad:
            - nivel: LICENCIATURA
              estadoNivel: TITULADO
              conCedulaProfesional: false
              cedulaProfesional: null
            - nivel: MAESTRIA
              estadoNivel: TITULADO
              conCedulaProfesional: true
              cedulaProfesional: '12345678'
      required:
        - persona
        - domicilio
        - escolaridad
        - fechaIngreso
        - tipoContratacion
        - idRegion
        - idDireccion
        - idSubdireccion
        - idPuesto
      properties:
        persona:
          $ref: '#/components/schemas/Persona'
          x-stoplight:
            id: 1yvd9d9gpzspk
        domicilio:
          $ref: '#/components/schemas/Domicilio'
          x-stoplight:
            id: 0yjlcc812o9o1
        escolaridad:
          type: array
          x-stoplight:
            id: 5d72q7jwipk1b
          minItems: 1
          items:
            $ref: '#/components/schemas/Escolaridad'
            x-stoplight:
              id: qer2gzyyk8okf
        fechaIngreso:
          type: string
          x-stoplight:
            id: wdy6ow3fslntt
          format: date
        tipoContratacion:
          $ref: '#/components/schemas/TipoContratacionEnum'
          x-stoplight:
            id: ik7wg04lltcgg
        idRegion:
          type: integer
          x-stoplight:
            id: a1q7dz7v5mdq9
        idDireccion:
          type: string
          x-stoplight:
            id: boowi8vzpkton
        idSubdireccion:
          type: string
          x-stoplight:
            id: zh9m61v7pyyzq
        idPuesto:
          type: string
          x-stoplight:
            id: 3vyfm67aisq6x
    Domicilio:
      title: DomicilioEmpleado
      x-stoplight:
        id: dsm6yd1sxwctg
      type: object
      description: Domicilio particular del empleado
      examples:
        - calle: Prolongación
          codigoPostal: '99999'
          colonia: Lomas de Prolongación
          municipio: Iztapalapa
          estado: CDMX
          ciudad: México
      required:
        - calle
        - codigoPostal
        - colonia
        - municipio
        - ciudad
        - estado
      properties:
        calle:
          type: string
          x-stoplight:
            id: chbn8upr51erf
        codigoPostal:
          type: string
          x-stoplight:
            id: 056p06a2j714p
          minLength: 5
          maxLength: 5
        colonia:
          type: string
          x-stoplight:
            id: 8x4osm8qnfns4
        municipio:
          type: string
          x-stoplight:
            id: ruu95nkca4g1h
        ciudad:
          type: string
          x-stoplight:
            id: pvbducyurysn9
        estado:
          type: string
          x-stoplight:
            id: dmhqr9a3xstf8
    Persona:
      title: Persona
      x-stoplight:
        id: 0iql6hgq28bre
      type: object
      description: Atributos que tiene una persona
      examples:
        - nombre: Fabian
          apellidoPaterno: Cortez
          apellidoMaterno: Estrada
          fechaNacimiento: '1998-01-01'
          edad: 26
          genero: MASCULINO
          numeroSeguroSocial: '12345678965'
          rfc: COEF980101ABC
          curp: COEF980101HDFABCXX
          correoElectronico: fabian.cortez@correo.com
          telefono: '5512345678'
          contactoEmergenciaNombre: Carolina Cortez Estrada
          contactoEmergenciaTelefono: '5598745632'
      required:
        - nombre
        - apellidoPaterno
        - apellidoMaterno
        - curp
        - rfc
        - numeroSeguroSocial
        - fechaNacimiento
        - edad
        - genero
        - telefonoPersonal
        - correoElectronicoPersonal
        - contactoEmergenciaNombre
        - contactoEmergenciaTelefono
      properties:
        nombre:
          type: string
          x-stoplight:
            id: 4vxs42tgyyole
        apellidoPaterno:
          type: string
          x-stoplight:
            id: jezjc4droemva
        apellidoMaterno:
          type: string
          x-stoplight:
            id: z6okx1m1lgx6p
        curp:
          type: string
          x-stoplight:
            id: ezkzkta9jq8ux
          minLength: 18
          maxLength: 18
        rfc:
          type: string
          x-stoplight:
            id: zddhtkawg3h78
          minLength: 13
          maxLength: 13
        numeroSeguroSocial:
          type: string
          x-stoplight:
            id: un0t2eeiu2k0s
          minLength: 11
          maxLength: 11
        fechaNacimiento:
          type: string
          x-stoplight:
            id: j56xlbv53ik12
          format: date
        edad:
          type: integer
          x-stoplight:
            id: qi3sk0u2ui1xi
        genero:
          $ref: '#/components/schemas/GeneroEnum'
          x-stoplight:
            id: d3hrreuqel3uq
        telefonoPersonal:
          type: string
          x-stoplight:
            id: aovoq7ifm4w78
          minLength: 10
          maxLength: 10
        correoElectronicoPersonal:
          type: string
          x-stoplight:
            id: j049ngdf3718t
          format: email
        contactoEmergenciaNombre:
          type: string
          x-stoplight:
            id: qhhzyzz4t5qc0
        contactoEmergenciaTelefono:
          type: string
          x-stoplight:
            id: qcxvhfup30ouq
          minLength: 10
          maxLength: 10
    Empleado:
      title: Empleado
      x-stoplight:
        id: 9m99cxtgz3q1c
      type: object
      required:
        - idEmpleado
        - idDireccion
        - idSubdireccion
        - idPuesto
      properties:
        idEmpleado:
          type: string
          x-stoplight:
            id: myafa2fnybuv5
        idDireccion:
          type: string
          x-stoplight:
            id: nazqvlt9rcpaa
        idSubdireccion:
          type: string
          x-stoplight:
            id: 6quw534b4cf41
        idPuesto:
          type: string
          x-stoplight:
            id: pixazuooo111q
    Error:
      title: Error
      x-stoplight:
        id: 6g2k21cuqycj0
      type: object
      description: Error a mostrar en caso de alguna anomalía
      examples:
        - codigo: 12
          mensaje: Aquí va el mensaje del error personalizado.
      required:
        - codigo
        - mensaje
      properties:
        codigo:
          type: integer
          x-stoplight:
            id: ovrpmxh6eo3w8
        mensaje:
          type: string
          x-stoplight:
            id: l9nb3gjt8aehy
    GeneroEnum:
      title: GeneroEnum
      x-stoplight:
        id: 2hngh3fp26t3k
      enum:
        - MASCULINO
        - FEMENINO
        - NO_BINARIO
        - DESCONOCIDO
      description: Valores permitidos para el género de una persona.
    Escolaridad:
      title: Escolaridad
      x-stoplight:
        id: 45bqtlnoej3gh
      type: object
      examples:
        - nivel: LICENCIATURA
          estadoNivel: CREDITOS_CUBIERTOS
          conCedulaProfesional: false
          cedulaProfesional: null
      description: Escolaridad de una persona u empleado
      required:
        - nivel
        - carrera
        - estadoNivel
        - conCedulaProfesional
        - cedulaProfesional
      properties:
        nivel:
          $ref: '#/components/schemas/EscolaridadesEnum'
          x-stoplight:
            id: v6plghb2z1y2h
        carrera:
          type: string
          x-stoplight:
            id: 4mgvs6bze6az6
        estadoNivel:
          $ref: '#/components/schemas/EstadoEscolaridadEnum'
          x-stoplight:
            id: eoc1unktk22m0
        conCedulaProfesional:
          type: boolean
          x-stoplight:
            id: cdax02p05vavh
        cedulaProfesional:
          type:
            - string
            - 'null'
          x-stoplight:
            id: i008hrw387hye
          minLength: 7
          maxLength: 8
    EscolaridadesEnum:
      title: EscolaridadesEnum
      x-stoplight:
        id: b0vkgsn675z45
      enum:
        - TECNICO
        - LICENCIATURA
        - MAESTRIA
        - ESPECIALIDAD
        - DOCTORADO
        - BACHILLERATO
        - DIPLOMADO
      description: Escolaridades permitidas
    EstadoEscolaridadEnum:
      title: EstadoEscolaridadEnum
      x-stoplight:
        id: jtzmbyk1m4drc
      enum:
        - CREDITOS_CUBIERTOS
        - CERTIFICADO
        - PASANTE
        - TITULADO
        - TRAMITE_TITULACION
        - TRUNCA
      description: Estado que tiene una escolaridad
    Items:
      title: Items
      x-stoplight:
        id: fthrm3hcau1dq
      type: object
      required:
        - id
        - nombre
      properties:
        id:
          type: string
          x-stoplight:
            id: m35sa3z03os56
        nombre:
          type: string
          x-stoplight:
            id: cr3563tmajs4v
      description: 'Obtiene los campos registrados, en pares ordenados'
    TipoContratacionEnum:
      title: TipoContratacionEnum
      x-stoplight:
        id: yx0yt7b5j2jic
      enum:
        - SP
        - EE
        - INCA
      description: Tipos de contratación que pueda ser un empleado
  requestBodies: {}
  responses: {}
  securitySchemes: {}
x-extension-1: null

