@startuml
'https://plantuml.com/sequence-diagram

actor Usuario as user
box "Frontend" #LightPink
    participant ":AgregarEmpleadoPage" as usuarioPage
    participant ":ServicioEmpleado" as service
    participant ":CodigoAutogenerado" as code
end box
box "Backend" #LightGreen
    participant ":Backend" as back
end box

user -> usuarioPage: Da clic en Page Agregar \nEmpleado
rnote over usuarioPage
Antes de mostrar la página, se hacen peticiones
GET al backend para obtener  niveles escolares,
Regiones, Direcciones, Subdirecciones, Tipos
de Plaza, Puestos y Roles.
end note
usuarioPage --> user: datosNecesarios
user -> usuarioPage: Llena formulario
usuarioPage -> usuarioPage: ValidarDatosForma
usuarioPage -> service: crearNuevoEmpleado(NewUsuarioDto)
service -> code: crearNuevoEmpleado(NewUsuarioDto)
code -> back: POST /api/empleados + JSON
back --> code: 201 Created + JSON
code --> service: 201 Created + JSON
service --> usuarioPage: EmpleadoDto

@enduml