@startuml
'https://plantuml.com/sequence-diagram

actor Usuario as user
box #LightPink
    participant ":Frontend" as front
end box
box "Backend" #LightGreen
    participant ":ControladorEmpleados" as controller
    participant ":ServicioEmpleados" as service
    participant ":RepositorioEmpleados" as repository
end box
box "Azure" #LightBlue
    database ":PostgreSQL" as db
end box
@enduml