/**
 * Sistema Integración Divisional API
 * Proyecto personal de Miguel Guzman. \"Sistema de Integración Divisional\" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cbi2193011275@izt.uam.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EstadoCivilEnum = 'CASADO' | 'CASADA' | 'SOLTERO' | 'SOLTERA' | 'VIUDO' | 'VIUDA' | 'SEPARADO' | 'SEPARADA' | 'DIVORCIADO' | 'DIVORCIADA' | 'UNION_LIBRE';

export const EstadoCivilEnum = {
    Casado: 'CASADO' as EstadoCivilEnum,
    Casada: 'CASADA' as EstadoCivilEnum,
    Soltero: 'SOLTERO' as EstadoCivilEnum,
    Soltera: 'SOLTERA' as EstadoCivilEnum,
    Viudo: 'VIUDO' as EstadoCivilEnum,
    Viuda: 'VIUDA' as EstadoCivilEnum,
    Separado: 'SEPARADO' as EstadoCivilEnum,
    Separada: 'SEPARADA' as EstadoCivilEnum,
    Divorciado: 'DIVORCIADO' as EstadoCivilEnum,
    Divorciada: 'DIVORCIADA' as EstadoCivilEnum,
    UnionLibre: 'UNION_LIBRE' as EstadoCivilEnum
};

