/**
 * Sistema Integración Divisional API
 * Proyecto personal de Miguel Guzman. \"Sistema de Integración Divisional\" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gzm98.miguel@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Estado que tiene una escolaridad
 */
export type EstadosNivelesEscolaridadesEnum = 'CREDITOS_CUBIERTOS' | 'CERTIFICADO' | 'PASANTE' | 'TITULADO' | 'TRAMITE_TITULACION' | 'TRUNCA';

export const EstadosNivelesEscolaridadesEnum = {
    CreditosCubiertos: 'CREDITOS_CUBIERTOS' as EstadosNivelesEscolaridadesEnum,
    Certificado: 'CERTIFICADO' as EstadosNivelesEscolaridadesEnum,
    Pasante: 'PASANTE' as EstadosNivelesEscolaridadesEnum,
    Titulado: 'TITULADO' as EstadosNivelesEscolaridadesEnum,
    TramiteTitulacion: 'TRAMITE_TITULACION' as EstadosNivelesEscolaridadesEnum,
    Trunca: 'TRUNCA' as EstadosNivelesEscolaridadesEnum
};

