/**
 * Sistema Integración Divisional API
 * Proyecto personal de Miguel Guzman. \"Sistema de Integración Divisional\" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gzm98.miguel@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MotivoBajaEnum = 'TERMINO_CONTRATO' | 'RENUNCIA' | 'LIQUIDACION';

export const MotivoBajaEnum = {
    TerminoContrato: 'TERMINO_CONTRATO' as MotivoBajaEnum,
    Renuncia: 'RENUNCIA' as MotivoBajaEnum,
    Liquidacion: 'LIQUIDACION' as MotivoBajaEnum
};

