/**
 * Sistema Integración Divisional API
 * Proyecto personal de Miguel Guzman. \"Sistema de Integración Divisional\" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gzm98.miguel@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Persona } from './persona';
import { Escolaridad } from './escolaridad';
import { Domicilio } from './domicilio';


export interface NewEmpleado { 
    persona: Persona;
    domicilio: Domicilio;
    escolaridades: Array<Escolaridad>;
    fechaIngreso: string;
    idTipoPlaza: string;
    idRegion: string;
    idDireccion: string;
    idSubdireccion: string;
    idPuesto: string;
    roles: Array<string>;
}

