/**
 * Sistema Integración Divisional API
 * Proyecto personal de Miguel Guzman. \"Sistema de Integración Divisional\" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: gzm98.miguel@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Escolaridades permitidas
 */
export type NivelesEscolaridadesEnum = 'TECNICO' | 'LICENCIATURA' | 'MAESTRIA' | 'ESPECIALIDAD' | 'DOCTORADO' | 'BACHILLERATO' | 'DIPLOMADO';

export const NivelesEscolaridadesEnum = {
    Tecnico: 'TECNICO' as NivelesEscolaridadesEnum,
    Licenciatura: 'LICENCIATURA' as NivelesEscolaridadesEnum,
    Maestria: 'MAESTRIA' as NivelesEscolaridadesEnum,
    Especialidad: 'ESPECIALIDAD' as NivelesEscolaridadesEnum,
    Doctorado: 'DOCTORADO' as NivelesEscolaridadesEnum,
    Bachillerato: 'BACHILLERATO' as NivelesEscolaridadesEnum,
    Diplomado: 'DIPLOMADO' as NivelesEscolaridadesEnum
};

