/**
 * Sistema Integración Divisional API
 * Proyecto personal de Miguel Guzman. \"Sistema de Integración Divisional\" para la empresa Agricultura en la Dirección General de Enlace y Coordinación (DGEC). Esta API está elaborada solo con fines educativos y de practica personal.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cbi2193011275@izt.uam.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface URIDocumentosPersona { 
    ine: string;
    actaNacimiento: string;
    numeroSeguroSocial: string;
    curp: string;
    rfc: string;
    comprobanteDomicilio: string;
    titulosProfesionales: Array<string>;
    cedulasProfesionales?: Array<string>;
}

