services:
  db:
    container_name: db_sid
    image: postgres:16.3
    #restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PGPASSWORD}
      POSTGRES_DB: ${DB_PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data

  #pgadmin:
    #image: dpage/pgadmin4
    #container_name: pgadmin4_container
    #restart: always
    #ports:
      #- "8888:80"
    #environment:
      #PGADMIN_DEFAULT_EMAIL: miguel@correo.mx
      #PGADMIN_DEFAULT_PASSWORD: 1234