spring:
  datasource:
    url: jdbc:postgresql://${DB_PGHOST}:${DB_PGPORT}/${DB_PGDATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${DB_PGUSER}
    password: ${DB_PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://agriculturadgec.b2clogin.com/6ac852c4-0fec-4c09-8f6d-72857f0c87b8/v2.0/
          jwk-set-uri: https://agriculturadgec.b2clogin.com/agriculturadgec.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_login_email-password
          jws-algorithms: RS256

azure:
  ad:
    b2c:
      tenant: agriculturadgec.onmicrosoft.com
      client-id: fc405a63-8164-474c-8744-b00fc0c5a414
      client-secret: ${AZURE_TENANT_CLIENT_SECRET} # Tiene una fecha de expiración

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /doc