spring:
  #h2:
  #  console:
  #    enabled: true
  datasource:
    url: jdbc:postgresql://${AZURE_PGHOST}:${AZURE_PGPORT}/${AZURE_PGDATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${AZURE_PGUSER}
    password: ${AZURE_PGPASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    #properties:
    #  hibernate:
    #    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect