spring:
  datasource:
    url: jdbc:postgresql://${AZURE_PGHOST}:${AZURE_PGPORT}/${AZURE_PGDATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${AZURE_PGUSER}
    password: ${AZURE_PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none